Added function generate_twospirals from matlab
ATISLabs/SyntheticDatasets.jl pull request #17
Opened 2020-09-04 23:09 UTC by Sergiorezende22

Adicionei a função generate_twospirals do matlab.

2020-09-05 15:26 UTC, filipebraida requested changes
Tem como adicionar testes? Ainda não estamos fazendo testes elaborados, mas seria legal ter no mínimo se a função funciona.

2020-09-08 17:52 UTC, Sergiorezende22 commented
Adicionei os teste que você pediu professor, aconteceu o conflito pois foram feitos outros testes desde que eu clonei o master.

2020-09-09 14:37 UTC, filipebraida commented
Eu dei uma atualizada no projeto.
Está falando o README file.

Além disso, eu vou fazer um comentário no código.

2020-09-09 14:39 UTC, filipebraida requested changes
Faltando também o README

2020-09-09 14:39 UTC, filipebraida commented on src/matlab.jl
> +   return [d1; d2];
Acho que podemos deixar no padrão das outras funções de classificação. Retornando um DataFrame. Só tomando cuidado que a label deveria ser Int.

2020-09-10 18:45 UTC, Sergiorezende22 commented on src/matlab.jl
> +   return [d1; d2];
Feito

2020-09-10 20:22 UTC, filipebraida approved these changes

2020-09-10 20:22 UTC, merged