[#1] Feature/generate_hastie_10_2
ATISLabs/SyntheticDatasets.jl pull request #26
Opened 2020-09-09 02:45 UTC by nicolasmagalhaes

added generate_hastie_10_2 from sklearn
added tests for said function

2020-09-09 14:29 UTC, filipebraida commented
Faltando o README

2020-09-09 14:40 UTC, filipebraida requested changes
Faltando o README

2020-09-09 15:17 UTC, nicolasmagalhaes commented
> Faltando o README

adicionei

2020-09-10 20:41 UTC, filipebraida approved these changes

2020-09-10 20:42 UTC, merged